// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "Extension.76a44612-da86-4301-897a-fef9309a016b";
        public const string Name = "BCUnit Extension";
        public const string Description = @"BC Unit Framework -  BellevueCollege, Computer Science  2022";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "JHTQ";
        public const string Tags = "";
    }
}
