// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ExtensionString = "097cac92-5c56-4372-8db7-2e279a3a25cb";
        public static Guid Extension = new Guid(ExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int TopLevelMenu = 0x1021;
        public const int MyCommandRunSolution = 0x0100;
        public const int MyCommandRunProject = 0x0101;
    }
}